changes

diff --git a/.github/workflows/infrastructure.yml b/.github/workflows/infrastructure.yml
--- a/.github/workflows/infrastructure.yml
+++ b/.github/workflows/infrastructure.yml
@@ -33,6 +33,11 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
+      - name: Debug workspace
+        run: |
+          pwd
+          ls -R
+
       - name: Download deployment output
         uses: actions/download-artifact@v4
         with:
@@ -49,6 +54,10 @@ jobs:
       - name: Extract version from project
         run: |
           CSPROJ="src/project.csproj"
+          if [ ! -f "$CSPROJ" ]; then
+            echo "ERROR: File not found: $CSPROJ"
+            exit 1
+          fi
           VERSION=$(xmllint --xpath 'string(//Version|//PropertyGroup/Version)' "$CSPROJ")
           [  -z "$VERSION"  ] && echo "Missing <Version> in $CSPROJ" && exit 1
           echo "VERSION=$VERSION" >> $GITHUB_ENV
